services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=invext'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_PASSWORD=1234'
    ports:
      - '3306:3306'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
